// Compact country dataset: [name_uz, iso2, capital_uz, continent_uz]
// continent codes: EU EurOpa, AS Osiyo, AF Afrika, NA Shimoliy Amerika,
//                  SA Janubiy Amerika, OC Okeaniya
export const COUNTRIES = [
  ["O'zbekiston","uz","Toshkent","AS"],
  ["Qozog'iston","kz","Astana","AS"],
  ["Qirg'iziston","kg","Bishkek","AS"],
  ["Tojikiston","tj","Dushanbe","AS"],
  ["Turkmaniston","tm","Ashxobod","AS"],
  ["Rossiya","ru","Moskva","EU"],
  ["Xitoy","cn","Pekin","AS"],
  ["Yaponiya","jp","Tokio","AS"],
  ["Janubiy Koreya","kr","Seul","AS"],
  ["Shimoliy Koreya","kp","Pxenyan","AS"],
  ["Hindiston","in","Yangi Dehli","AS"],
  ["Pokiston","pk","Islomobod","AS"],
  ["Afg'oniston","af","Kobul","AS"],
  ["Eron","ir","Tehron","AS"],
  ["Iroq","iq","Bag'dod","AS"],
  ["Turkiya","tr","Anqara","AS"],
  ["Suriya","sy","Damashq","AS"],
  ["Isroil","il","Quddus","AS"],
  ["Saudiya Arabistoni","sa","Ar-Riyod","AS"],
  ["BAA","ae","Abu-Dabi","AS"],
  ["Qatar","qa","Doha","AS"],
  ["Tailand","th","Bangkok","AS"],
  ["Vyetnam","vn","Hanoy","AS"],
  ["Indoneziya","id","Jakarta","AS"],
  ["Malayziya","my","Kuala-Lumpur","AS"],
  ["Filippin","ph","Manila","AS"],
  ["Singapur","sg","Singapur","AS"],
  ["Mongoliya","mn","Ulan-Bator","AS"],
  ["Nepal","np","Katmandu","AS"],
  ["Bangladesh","bd","Dakka","AS"],
  ["Shri-Lanka","lk","Kolombo","AS"],
  ["Ozarbayjon","az","Boku","AS"],
  ["Armaniston","am","Yerevan","AS"],
  ["Gruziya","ge","Tbilisi","AS"],

  ["Germaniya","de","Berlin","EU"],
  ["Fransiya","fr","Parij","EU"],
  ["Italiya","it","Rim","EU"],
  ["Ispaniya","es","Madrid","EU"],
  ["Portugaliya","pt","Lissabon","EU"],
  ["Buyuk Britaniya","gb","London","EU"],
  ["Irlandiya","ie","Dublin","EU"],
  ["Niderlandiya","nl","Amsterdam","EU"],
  ["Belgiya","be","Bryussel","EU"],
  ["Shveysariya","ch","Bern","EU"],
  ["Avstriya","at","Vena","EU"],
  ["Polsha","pl","Varshava","EU"],
  ["Chexiya","cz","Praga","EU"],
  ["Slovakiya","sk","Bratislava","EU"],
  ["Vengriya","hu","Budapesht","EU"],
  ["Ruminiya","ro","Buxarest","EU"],
  ["Bolgariya","bg","Sofiya","EU"],
  ["Gretsiya","gr","Afina","EU"],
  ["Shvetsiya","se","Stokgolm","EU"],
  ["Norvegiya","no","Oslo","EU"],
  ["Finlyandiya","fi","Xelsinki","EU"],
  ["Daniya","dk","Kopengagen","EU"],
  ["Islandiya","is","Reykyavik","EU"],
  ["Ukraina","ua","Kiyev","EU"],
  ["Belarus","by","Minsk","EU"],
  ["Moldova","md","Kishinyov","EU"],
  ["Serbiya","rs","Belgrad","EU"],
  ["Xorvatiya","hr","Zagreb","EU"],
  ["Sloveniya","si","Lyublyana","EU"],
  ["Bosniya va Gertsegovina","ba","Sarayevo","EU"],
  ["Albaniya","al","Tirana","EU"],
  ["Estoniya","ee","Tallin","EU"],
  ["Latviya","lv","Riga","EU"],
  ["Litva","lt","Vilnyus","EU"],

  ["Misr","eg","Qohira","AF"],
  ["Liviya","ly","Tripoli","AF"],
  ["Tunis","tn","Tunis","AF"],
  ["Jazoir","dz","Jazoir","AF"],
  ["Marokash","ma","Rabat","AF"],
  ["Sudan","sd","Xartum","AF"],
  ["Efiopiya","et","Addis-Abeba","AF"],
  ["Keniya","ke","Nayrobi","AF"],
  ["Tanzaniya","tz","Dodoma","AF"],
  ["Uganda","ug","Kampala","AF"],
  ["Nigeriya","ng","Abudja","AF"],
  ["Gana","gh","Akkra","AF"],
  ["Senegal","sn","Dakar","AF"],
  ["Janubiy Afrika","za","Pretoriya","AF"],
  ["Zimbabve","zw","Xarare","AF"],
  ["Madagaskar","mg","Antananarivu","AF"],
  ["Angola","ao","Luanda","AF"],

  ["AQSh","us","Vashington","NA"],
  ["Kanada","ca","Ottava","NA"],
  ["Meksika","mx","Mexiko","NA"],
  ["Kuba","cu","Gavana","NA"],
  ["Yamayka","jm","Kingston","NA"],
  ["Panama","pa","Panama","NA"],
  ["Kosta-Rika","cr","San-Xose","NA"],
  ["Gvatemala","gt","Gvatemala","NA"],

  ["Braziliya","br","Braziliya","SA"],
  ["Argentina","ar","Buenos-Ayres","SA"],
  ["Chili","cl","Santyago","SA"],
  ["Peru","pe","Lima","SA"],
  ["Kolumbiya","co","Bogota","SA"],
  ["Venesuela","ve","Karakas","SA"],
  ["Urugvay","uy","Montevideo","SA"],
  ["Paragvay","py","Asunsion","SA"],
  ["Boliviya","bo","La-Pas","SA"],
  ["Ekvador","ec","Kito","SA"],

  ["Avstraliya","au","Kanberra","OC"],
  ["Yangi Zelandiya","nz","Vellington","OC"],
  ["Fiji","fj","Suva","OC"],
  ["Papua-Yangi Gvineya","pg","Port-Morsbi","OC"],
];

export const CONTINENT_NAMES = {
  EU: "Yevropa", AS: "Osiyo", AF: "Afrika",
  NA: "Shimoliy Amerika", SA: "Janubiy Amerika", OC: "Okeaniya",
};

export function flagUrl(iso2) {
  return `https://flagcdn.com/w320/${iso2}.png`;
}
